//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS_Diabetes_App {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LS_Diabetes_App.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date of birth.
        /// </summary>
        internal static string BirthDate_PlaceHolder {
            get {
                return ResourceManager.GetString("BirthDate_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm Passwod.
        /// </summary>
        internal static string ConfirmPassword_PlaceHolder {
            get {
                return ResourceManager.GetString("ConfirmPassword_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diabetes type.
        /// </summary>
        internal static string DiabetesType_Label {
            get {
                return ResourceManager.GetString("DiabetesType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drugs.
        /// </summary>
        internal static string Drugs_Label {
            get {
                return ResourceManager.GetString("Drugs_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Female.
        /// </summary>
        internal static string Female_RadioButton {
            get {
                return ResourceManager.GetString("Female_RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name.
        /// </summary>
        internal static string FirstName_PlaceHolder {
            get {
                return ResourceManager.GetString("FirstName_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgot Password ?.
        /// </summary>
        internal static string ForgotPassword_Label {
            get {
                return ResourceManager.GetString("ForgotPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Glucometer.
        /// </summary>
        internal static string Glucometer_Label {
            get {
                return ResourceManager.GetString("Glucometer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Glycemia.
        /// </summary>
        internal static string Home_Glucose_Lavel_Label {
            get {
                return ResourceManager.GetString("Home_Glucose_Lavel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insulin.
        /// </summary>
        internal static string Insuline_Label {
            get {
                return ResourceManager.GetString("Insuline_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insulin pump therapy.
        /// </summary>
        internal static string InsulinPumpTherapy_Label {
            get {
                return ResourceManager.GetString("InsulinPumpTherapy_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name.
        /// </summary>
        internal static string LastName_PlaceHolder {
            get {
                return ResourceManager.GetString("LastName_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Male.
        /// </summary>
        internal static string Male_RadioButton {
            get {
                return ResourceManager.GetString("Male_RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note.
        /// </summary>
        internal static string Note_Label {
            get {
                return ResourceManager.GetString("Note_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string Password_PlaceHolder {
            get {
                return ResourceManager.GetString("Password_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Postition.
        /// </summary>
        internal static string Position_Label {
            get {
                return ResourceManager.GetString("Position_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arterial pressure.
        /// </summary>
        internal static string Pression_Label {
            get {
                return ResourceManager.GetString("Pression_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign In.
        /// </summary>
        internal static string SignIn_Label {
            get {
                return ResourceManager.GetString("SignIn_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign Up.
        /// </summary>
        internal static string SignUp_Label {
            get {
                return ResourceManager.GetString("SignUp_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step.
        /// </summary>
        internal static string Step_Label {
            get {
                return ResourceManager.GetString("Step_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time.
        /// </summary>
        internal static string Time_Label {
            get {
                return ResourceManager.GetString("Time_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unit.
        /// </summary>
        internal static string Unit_Label {
            get {
                return ResourceManager.GetString("Unit_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-mail.
        /// </summary>
        internal static string UserName_PlaceHolder {
            get {
                return ResourceManager.GetString("UserName_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weight.
        /// </summary>
        internal static string Weight_Label {
            get {
                return ResourceManager.GetString("Weight_Label", resourceCulture);
            }
        }
    }
}
